apiVersion: v1
kind: Secret
metadata:
  name: db-prod
type: Opaque
data:
  config: ewogICAgIkRhdGEiOiB7CiAgICAgICAgIk15U3FsIjogewogICAgICAgICAgICAiQ29ubmVjdGlvbiI6IHsKICAgICAgICAgICAgICAgICJob3N0IjogImRiIiwKICAgICAgICAgICAgICAgICJwb3J0IjogMzMwNiwKICAgICAgICAgICAgICAgICJ1c2VyIGlkIjogInJvb3QiLAogICAgICAgICAgICAgICAgInBhc3N3b3JkIjogInRlc3QiLAogICAgICAgICAgICAgICAgImRhdGFiYXNlIjogImFwcC1wcm9kIgogICAgICAgICAgICB9CiAgICAgICAgfQogICAgfQp9Cg==
