kind: Service
apiVersion: v1
metadata:
  name: boxboat-blog-prod
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      nodePort: 30080
      protocol: TCP
  selector:
    app: boxboat-blog-prod
